# Generated by Django 4.2.7 on 2026-02-20 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_location', models.CharField(max_length=200, verbose_name='Бастапқы орналасқан жері')),
                ('destination_location', models.CharField(max_length=200, verbose_name='Мақсатты орналасқан жері')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тасымалданатын саны')),
                ('transport_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тасымалдаушы компания')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Жүргізуші аты')),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Жүргізуші телефоны')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Көлік нөмірі')),
                ('planned_date', models.DateTimeField(verbose_name='Жоспарланған күні')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='Нақты күні')),
                ('status', models.CharField(choices=[('planned', 'Жоспарланған'), ('in_transit', 'Тасымалдауда'), ('completed', 'Аяқталған'), ('cancelled', 'Бас тартылған')], default='planned', max_length=20, verbose_name='Күйі')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ескертпелер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL, verbose_name='Құрған пайдаланушы')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='materials.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Тасымал маршруты',
                'verbose_name_plural': 'Тасымал маршруттары',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='TransportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Орналасқан жері')),
                ('status', models.CharField(max_length=50, verbose_name='Күйі')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ескертпелер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Уақыты')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='transport.transportroute', verbose_name='Маршрут')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_updates', to=settings.AUTH_USER_MODEL, verbose_name='Жаңартқан пайдаланушы')),
            ],
            options={
                'verbose_name': 'Тасымал тарихы',
                'verbose_name_plural': 'Тасымал тарихы',
                'ordering': ['-created_at'],
            },
        ),
    ]
