# Generated by Django 4.2.7 on 2026-02-20 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Атауы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сипаттама')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
            ],
            options={
                'verbose_name': 'Материал санаты',
                'verbose_name_plural': 'Материал санаттары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Атауы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сипаттама')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Саны')),
                ('unit', models.CharField(choices=[('kg', 'Килограмм'), ('ton', 'Тонна'), ('m3', 'Кубикалық метр'), ('m2', 'Шаршы метр'), ('piece', 'Дана'), ('pack', 'Пакет')], default='piece', max_length=20, verbose_name='Өлшем бірлігі')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бірлік бағасы')),
                ('status', models.CharField(choices=[('available', 'Қолжетімді'), ('in_transit', 'Тасымалдауда'), ('delivered', 'Жеткізілген'), ('reserved', 'Резервтелген')], default='available', max_length=20, verbose_name='Күйі')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Орналасқан жері')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Жеткізуші')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Жеткізу күні')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='materials.materialcategory', verbose_name='Санаты')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to=settings.AUTH_USER_MODEL, verbose_name='Құрған пайдаланушы')),
            ],
            options={
                'verbose_name': 'Құрылыс материалы',
                'verbose_name_plural': 'Құрылыс материалдары',
                'ordering': ['-created_at'],
            },
        ),
    ]
